### ISSUE TITLE
Adding styles and scripts

### ISSUE THREAD

**Issue by priteshparmar1092** [rtCamp/rtpanel#115]
I am trying to add style using rtp_head but its not working.

function custom_rtp_head() {
wp_enqueue_style( 'rt-assignment-foundation', get_template_directory_uri() . '/css/foundation/css/foundation.min.css', '', '5.5.1' );
}
add_action( 'rtp_head', 'custom_rtp_head' );

**Comment by sagarjadhav** [comment]
I just test above code on my site and function works fine. Check your foundation.min.css file path or simply send me your site link.

**Comment by priteshparmar1092** [comment]
Thanks for your support. Can you please let me know about this issue- https://github.com/rtCamp/rtpanel-child-theme/issues/7

**Comment by sagarjadhav** [comment]
Hi,
Kindly check reply here https://github.com/rtCamp/rtpanel-child-theme/issues/7
