### ISSUE TITLE
Dutch language translation

### ISSUE THREAD

**Issue by herbie4** [rtCamp/rtpanel#117]
I added the full dutch language translation. 
Have a look at: https://rtcamp.com/translate/projects/rtpanel/nl/default
I hope you can have a look and integrate it into the next version. Thank you.
If it is easier I can fork and put in a pull request. Just let me know.

**Comment by manishsongirkar** [comment]
Thanks @herbie4 for contributing in rtPanel.
We will add this translation (.po file) in upcoming release.
Also, you can fork the rtPanel and feel free to send us pull request.
